#ifndef _CPU_OPCODES_H
#define _CPU_OPCODES_H

#include "cpu.h"
#include "mmu.h"
#include "register.h"

void load_cpu_opcodes(cpu_t *cpu, opfunc_t *arr);
void load_cpu_cb_opcodes(cpu_t *cpu, opfunc_t *arr);
void register_increment(cpu_t *cpu, reg16_t *reg, bool hi);

uint8_t increment(cpu_t *cpu, uint8_t current, uint8_t increment);
uint8_t decrement(cpu_t *cpu, uint8_t current, uint8_t decrement);
uint8_t add_8x8(cpu_t *cpu, uint8_t a, uint8_t b);
uint8_t adc_8x8(cpu_t *cpu, uint8_t a, uint8_t b);
uint8_t sub_8x8(cpu_t *cpu, uint8_t a, uint8_t b);
uint8_t subc_8x8(cpu_t *cpu, uint8_t a, uint8_t b);
uint8_t decr_values(cpu_t *cpu, uint8_t a, uint8_t b);
uint8_t or_8x8(cpu_t *cpu, uint8_t a, uint8_t b);
uint8_t and_8x8(cpu_t *cpu, uint8_t a, uint8_t b);
void cmp_values(cpu_t *cpu, uint8_t a, uint8_t b);

uint8_t rot_lc(cpu_t *cpu, uint8_t a);
uint8_t rot_l(cpu_t *cpu, uint8_t a);
uint8_t rot_rc(cpu_t *cpu, uint8_t a);
uint8_t rot_r(cpu_t *cpu, uint8_t a);

bool test_half_carry(uint8_t old_value, uint8_t increment);
bool test_8bit_carry(uint8_t old_value, uint8_t increment);

void reg_a_xor(cpu_t *cpu, uint8_t value);
void reg_load(cpu_t *cpu, mmu_t *mmu);
void opfunc_halt(cpu_t *cpu, mmu_t *mmu);

void pop(cpu_t *cpu, mmu_t *mmu, reg16_t *dest);
void push_reg(cpu_t *cpu, mmu_t *mmu, reg16_t *origin);
void push(cpu_t *cpu, mmu_t *mmu, uint8_t hi, uint8_t lo);
void ret(cpu_t *cpu, mmu_t *mmu);
void jmp(cpu_t *cpu, mmu_t *mmu);
void call(cpu_t *cpu, mmu_t *mmu);

void opfunc_00(cpu_t *cpu, mmu_t *mmu);
void opfunc_01(cpu_t *cpu, mmu_t *mmu);
void opfunc_02(cpu_t *cpu, mmu_t *mmu);
void opfunc_03(cpu_t *cpu, mmu_t *mmu);
void opfunc_04(cpu_t *cpu, mmu_t *mmu);
void opfunc_05(cpu_t *cpu, mmu_t *mmu);
void opfunc_06(cpu_t *cpu, mmu_t *mmu);
void opfunc_07(cpu_t *cpu, mmu_t *mmu);
void opfunc_08(cpu_t *cpu, mmu_t *mmu);
void opfunc_09(cpu_t *cpu, mmu_t *mmu);
void opfunc_0A(cpu_t *cpu, mmu_t *mmu);
void opfunc_0B(cpu_t *cpu, mmu_t *mmu);
void opfunc_0C(cpu_t *cpu, mmu_t *mmu);
void opfunc_0D(cpu_t *cpu, mmu_t *mmu);
void opfunc_0E(cpu_t *cpu, mmu_t *mmu);
void opfunc_0F(cpu_t *cpu, mmu_t *mmu);
void opfunc_10(cpu_t *cpu, mmu_t *mmu);
void opfunc_11(cpu_t *cpu, mmu_t *mmu);
void opfunc_12(cpu_t *cpu, mmu_t *mmu);
void opfunc_13(cpu_t *cpu, mmu_t *mmu);
void opfunc_14(cpu_t *cpu, mmu_t *mmu);
void opfunc_15(cpu_t *cpu, mmu_t *mmu);
void opfunc_16(cpu_t *cpu, mmu_t *mmu);
void opfunc_17(cpu_t *cpu, mmu_t *mmu);
void opfunc_18(cpu_t *cpu, mmu_t *mmu);
void opfunc_19(cpu_t *cpu, mmu_t *mmu);
void opfunc_1A(cpu_t *cpu, mmu_t *mmu);
void opfunc_1B(cpu_t *cpu, mmu_t *mmu);
void opfunc_1C(cpu_t *cpu, mmu_t *mmu);
void opfunc_1D(cpu_t *cpu, mmu_t *mmu);
void opfunc_1E(cpu_t *cpu, mmu_t *mmu);
void opfunc_1F(cpu_t *cpu, mmu_t *mmu);
void opfunc_20(cpu_t *cpu, mmu_t *mmu);
void opfunc_21(cpu_t *cpu, mmu_t *mmu);
void opfunc_22(cpu_t *cpu, mmu_t *mmu);
void opfunc_23(cpu_t *cpu, mmu_t *mmu);
void opfunc_24(cpu_t *cpu, mmu_t *mmu);
void opfunc_25(cpu_t *cpu, mmu_t *mmu);
void opfunc_26(cpu_t *cpu, mmu_t *mmu);
void opfunc_27(cpu_t *cpu, mmu_t *mmu);
void opfunc_28(cpu_t *cpu, mmu_t *mmu);
void opfunc_29(cpu_t *cpu, mmu_t *mmu);
void opfunc_2A(cpu_t *cpu, mmu_t *mmu);
void opfunc_2B(cpu_t *cpu, mmu_t *mmu);
void opfunc_2C(cpu_t *cpu, mmu_t *mmu);
void opfunc_2D(cpu_t *cpu, mmu_t *mmu);
void opfunc_2E(cpu_t *cpu, mmu_t *mmu);
void opfunc_2F(cpu_t *cpu, mmu_t *mmu);
void opfunc_30(cpu_t *cpu, mmu_t *mmu);
void opfunc_31(cpu_t *cpu, mmu_t *mmu);
void opfunc_32(cpu_t *cpu, mmu_t *mmu);
void opfunc_33(cpu_t *cpu, mmu_t *mmu);
void opfunc_34(cpu_t *cpu, mmu_t *mmu);
void opfunc_35(cpu_t *cpu, mmu_t *mmu);
void opfunc_36(cpu_t *cpu, mmu_t *mmu);
void opfunc_37(cpu_t *cpu, mmu_t *mmu);
void opfunc_38(cpu_t *cpu, mmu_t *mmu);
void opfunc_39(cpu_t *cpu, mmu_t *mmu);
void opfunc_3A(cpu_t *cpu, mmu_t *mmu);
void opfunc_3B(cpu_t *cpu, mmu_t *mmu);
void opfunc_3C(cpu_t *cpu, mmu_t *mmu);
void opfunc_3D(cpu_t *cpu, mmu_t *mmu);
void opfunc_3E(cpu_t *cpu, mmu_t *mmu);
void opfunc_3F(cpu_t *cpu, mmu_t *mmu);
void opfunc_40(cpu_t *cpu, mmu_t *mmu);
void opfunc_41(cpu_t *cpu, mmu_t *mmu);
void opfunc_42(cpu_t *cpu, mmu_t *mmu);
void opfunc_43(cpu_t *cpu, mmu_t *mmu);
void opfunc_44(cpu_t *cpu, mmu_t *mmu);
void opfunc_45(cpu_t *cpu, mmu_t *mmu);
void opfunc_46(cpu_t *cpu, mmu_t *mmu);
void opfunc_47(cpu_t *cpu, mmu_t *mmu);
void opfunc_48(cpu_t *cpu, mmu_t *mmu);
void opfunc_49(cpu_t *cpu, mmu_t *mmu);
void opfunc_4A(cpu_t *cpu, mmu_t *mmu);
void opfunc_4B(cpu_t *cpu, mmu_t *mmu);
void opfunc_4C(cpu_t *cpu, mmu_t *mmu);
void opfunc_4D(cpu_t *cpu, mmu_t *mmu);
void opfunc_4E(cpu_t *cpu, mmu_t *mmu);
void opfunc_4F(cpu_t *cpu, mmu_t *mmu);
void opfunc_50(cpu_t *cpu, mmu_t *mmu);
void opfunc_51(cpu_t *cpu, mmu_t *mmu);
void opfunc_52(cpu_t *cpu, mmu_t *mmu);
void opfunc_53(cpu_t *cpu, mmu_t *mmu);
void opfunc_54(cpu_t *cpu, mmu_t *mmu);
void opfunc_55(cpu_t *cpu, mmu_t *mmu);
void opfunc_56(cpu_t *cpu, mmu_t *mmu);
void opfunc_57(cpu_t *cpu, mmu_t *mmu);
void opfunc_58(cpu_t *cpu, mmu_t *mmu);
void opfunc_59(cpu_t *cpu, mmu_t *mmu);
void opfunc_5A(cpu_t *cpu, mmu_t *mmu);
void opfunc_5B(cpu_t *cpu, mmu_t *mmu);
void opfunc_5C(cpu_t *cpu, mmu_t *mmu);
void opfunc_5D(cpu_t *cpu, mmu_t *mmu);
void opfunc_5E(cpu_t *cpu, mmu_t *mmu);
void opfunc_5F(cpu_t *cpu, mmu_t *mmu);
void opfunc_60(cpu_t *cpu, mmu_t *mmu);
void opfunc_61(cpu_t *cpu, mmu_t *mmu);
void opfunc_62(cpu_t *cpu, mmu_t *mmu);
void opfunc_63(cpu_t *cpu, mmu_t *mmu);
void opfunc_64(cpu_t *cpu, mmu_t *mmu);
void opfunc_65(cpu_t *cpu, mmu_t *mmu);
void opfunc_66(cpu_t *cpu, mmu_t *mmu);
void opfunc_67(cpu_t *cpu, mmu_t *mmu);
void opfunc_68(cpu_t *cpu, mmu_t *mmu);
void opfunc_69(cpu_t *cpu, mmu_t *mmu);
void opfunc_6A(cpu_t *cpu, mmu_t *mmu);
void opfunc_6B(cpu_t *cpu, mmu_t *mmu);
void opfunc_6C(cpu_t *cpu, mmu_t *mmu);
void opfunc_6D(cpu_t *cpu, mmu_t *mmu);
void opfunc_6E(cpu_t *cpu, mmu_t *mmu);
void opfunc_6F(cpu_t *cpu, mmu_t *mmu);
void opfunc_70(cpu_t *cpu, mmu_t *mmu);
void opfunc_71(cpu_t *cpu, mmu_t *mmu);
void opfunc_72(cpu_t *cpu, mmu_t *mmu);
void opfunc_73(cpu_t *cpu, mmu_t *mmu);
void opfunc_74(cpu_t *cpu, mmu_t *mmu);
void opfunc_75(cpu_t *cpu, mmu_t *mmu);
// 76 is opfunc_halt()
void opfunc_77(cpu_t *cpu, mmu_t *mmu);
void opfunc_78(cpu_t *cpu, mmu_t *mmu);
void opfunc_79(cpu_t *cpu, mmu_t *mmu);
void opfunc_7A(cpu_t *cpu, mmu_t *mmu);
void opfunc_7B(cpu_t *cpu, mmu_t *mmu);
void opfunc_7C(cpu_t *cpu, mmu_t *mmu);
void opfunc_7D(cpu_t *cpu, mmu_t *mmu);
void opfunc_7E(cpu_t *cpu, mmu_t *mmu);
void opfunc_7F(cpu_t *cpu, mmu_t *mmu);
void opfunc_80(cpu_t *cpu, mmu_t *mmu);
void opfunc_81(cpu_t *cpu, mmu_t *mmu);
void opfunc_82(cpu_t *cpu, mmu_t *mmu);
void opfunc_83(cpu_t *cpu, mmu_t *mmu);
void opfunc_84(cpu_t *cpu, mmu_t *mmu);
void opfunc_85(cpu_t *cpu, mmu_t *mmu);
void opfunc_86(cpu_t *cpu, mmu_t *mmu);
void opfunc_87(cpu_t *cpu, mmu_t *mmu);
void opfunc_88(cpu_t *cpu, mmu_t *mmu);
void opfunc_89(cpu_t *cpu, mmu_t *mmu);
void opfunc_8A(cpu_t *cpu, mmu_t *mmu);
void opfunc_8B(cpu_t *cpu, mmu_t *mmu);
void opfunc_8C(cpu_t *cpu, mmu_t *mmu);
void opfunc_8D(cpu_t *cpu, mmu_t *mmu);
void opfunc_8E(cpu_t *cpu, mmu_t *mmu);
void opfunc_8F(cpu_t *cpu, mmu_t *mmu);
void opfunc_90(cpu_t *cpu, mmu_t *mmu);
void opfunc_91(cpu_t *cpu, mmu_t *mmu);
void opfunc_92(cpu_t *cpu, mmu_t *mmu);
void opfunc_93(cpu_t *cpu, mmu_t *mmu);
void opfunc_94(cpu_t *cpu, mmu_t *mmu);
void opfunc_95(cpu_t *cpu, mmu_t *mmu);
void opfunc_96(cpu_t *cpu, mmu_t *mmu);
void opfunc_97(cpu_t *cpu, mmu_t *mmu);
void opfunc_98(cpu_t *cpu, mmu_t *mmu);
void opfunc_99(cpu_t *cpu, mmu_t *mmu);
void opfunc_9A(cpu_t *cpu, mmu_t *mmu);
void opfunc_9B(cpu_t *cpu, mmu_t *mmu);
void opfunc_9C(cpu_t *cpu, mmu_t *mmu);
void opfunc_9D(cpu_t *cpu, mmu_t *mmu);
void opfunc_9E(cpu_t *cpu, mmu_t *mmu);
void opfunc_9F(cpu_t *cpu, mmu_t *mmu);
void opfunc_A0(cpu_t *cpu, mmu_t *mmu);
void opfunc_A1(cpu_t *cpu, mmu_t *mmu);
void opfunc_A2(cpu_t *cpu, mmu_t *mmu);
void opfunc_A3(cpu_t *cpu, mmu_t *mmu);
void opfunc_A4(cpu_t *cpu, mmu_t *mmu);
void opfunc_A5(cpu_t *cpu, mmu_t *mmu);
void opfunc_A6(cpu_t *cpu, mmu_t *mmu);
void opfunc_A7(cpu_t *cpu, mmu_t *mmu);
void opfunc_A8(cpu_t *cpu, mmu_t *mmu);
void opfunc_A9(cpu_t *cpu, mmu_t *mmu);
void opfunc_AA(cpu_t *cpu, mmu_t *mmu);
void opfunc_AB(cpu_t *cpu, mmu_t *mmu);
void opfunc_AC(cpu_t *cpu, mmu_t *mmu);
void opfunc_AD(cpu_t *cpu, mmu_t *mmu);
void opfunc_AE(cpu_t *cpu, mmu_t *mmu);
void opfunc_AF(cpu_t *cpu, mmu_t *mmu);
void opfunc_B0(cpu_t *cpu, mmu_t *mmu);
void opfunc_B1(cpu_t *cpu, mmu_t *mmu);
void opfunc_B2(cpu_t *cpu, mmu_t *mmu);
void opfunc_B3(cpu_t *cpu, mmu_t *mmu);
void opfunc_B4(cpu_t *cpu, mmu_t *mmu);
void opfunc_B5(cpu_t *cpu, mmu_t *mmu);
void opfunc_B6(cpu_t *cpu, mmu_t *mmu);
void opfunc_B7(cpu_t *cpu, mmu_t *mmu);
void opfunc_B8(cpu_t *cpu, mmu_t *mmu);
void opfunc_B9(cpu_t *cpu, mmu_t *mmu);
void opfunc_BA(cpu_t *cpu, mmu_t *mmu);
void opfunc_BB(cpu_t *cpu, mmu_t *mmu);
void opfunc_BC(cpu_t *cpu, mmu_t *mmu);
void opfunc_BD(cpu_t *cpu, mmu_t *mmu);
void opfunc_BE(cpu_t *cpu, mmu_t *mmu);
void opfunc_BF(cpu_t *cpu, mmu_t *mmu);

void opfunc_C0(cpu_t *cpu, mmu_t *mmu);
void opfunc_C1(cpu_t *cpu, mmu_t *mmu);
void opfunc_C2(cpu_t *cpu, mmu_t *mmu);
void opfunc_C3(cpu_t *cpu, mmu_t *mmu);
void opfunc_C4(cpu_t *cpu, mmu_t *mmu);
void opfunc_C5(cpu_t *cpu, mmu_t *mmu);
void opfunc_C6(cpu_t *cpu, mmu_t *mmu);
void opfunc_C8(cpu_t *cpu, mmu_t *mmu);
void opfunc_C9(cpu_t *cpu, mmu_t *mmu);
void opfunc_CA(cpu_t *cpu, mmu_t *mmu);
void opfunc_CC(cpu_t *cpu, mmu_t *mmu);
void opfunc_CD(cpu_t *cpu, mmu_t *mmu);
void opfunc_CE(cpu_t *cpu, mmu_t *mmu);
void opfunc_D0(cpu_t *cpu, mmu_t *mmu);
void opfunc_D1(cpu_t *cpu, mmu_t *mmu);
void opfunc_D2(cpu_t *cpu, mmu_t *mmu);
void opfunc_D4(cpu_t *cpu, mmu_t *mmu);
void opfunc_D5(cpu_t *cpu, mmu_t *mmu);
void opfunc_D6(cpu_t *cpu, mmu_t *mmu);
void opfunc_D8(cpu_t *cpu, mmu_t *mmu);
void opfunc_D9(cpu_t *cpu, mmu_t *mmu);
void opfunc_DA(cpu_t *cpu, mmu_t *mmu);
void opfunc_DC(cpu_t *cpu, mmu_t *mmu);
void opfunc_DE(cpu_t *cpu, mmu_t *mmu);
void opfunc_E0(cpu_t *cpu, mmu_t *mmu);
void opfunc_E1(cpu_t *cpu, mmu_t *mmu);
void opfunc_E2(cpu_t *cpu, mmu_t *mmu);
void opfunc_E5(cpu_t *cpu, mmu_t *mmu);
void opfunc_E6(cpu_t *cpu, mmu_t *mmu);
void opfunc_EA(cpu_t *cpu, mmu_t *mmu);
void opfunc_EE(cpu_t *cpu, mmu_t *mmu);
void opfunc_F0(cpu_t *cpu, mmu_t *mmu);
void opfunc_F1(cpu_t *cpu, mmu_t *mmu);
void opfunc_F2(cpu_t *cpu, mmu_t *mmu);
void opfunc_F3(cpu_t *cpu, mmu_t *mmu);
void opfunc_F5(cpu_t *cpu, mmu_t *mmu);
void opfunc_F6(cpu_t *cpu, mmu_t *mmu);
void opfunc_FA(cpu_t *cpu, mmu_t *mmu);
void opfunc_FB(cpu_t *cpu, mmu_t *mmu);
void opfunc_FE(cpu_t *cpu, mmu_t *mmu);
void opfunc_FF(cpu_t *cpu, mmu_t *mmu);

// CB Opcodes
void opfunc_CB_7C(cpu_t *cpu, mmu_t *mmu);

#endif